### ISSUE TITLE
Unable to install ActorsHQ module

### ISSUE THREAD

**Issue by darthgera123** [synthesiaresearch/humanrf#11]
Hi I am trying to install ActorsHQ module via `pip3 install .` . My conda env consists of torch 1.13.1+cu117 and same for tinycudnn. However the setup.py is failing and not giving a definitive error message. Attached is the output. please help @isikmustafa @martinruenz 

https://pastebin.com/zH52A0vt

**Comment by wszswppx** [comment]
Hello, I have same issue with you. Have you solved it yet?

**Comment by darthgera123** [comment]
i used a workaround where i imported paths locally instead of using it like a library
like instead of import actors.datasets i did it as import datasets

**Comment by isikmustafa** [comment]
@darthgera123 please check the line 27 in the error message you received, you are missing the `glm` library.

Have you run the command below?
`sudo apt-get install libglm-dev`

**Comment by darthgera123** [comment]
is there a way to install this in conda? @isikmustafa

**Comment by darthgera123** [comment]
issue resolved
