### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by 2680347338** [synthesiaresearch/humanrf#12]
Hi, thanks for releasing the code and data for this amazing work!

I would like to ask about the Alpha matte that corresponds to the RGB image. How can I create an Alpha matte like in your dataset, and what is the tool you are using？

**Comment by martinruenz** [comment]
Hi there! You can either use off the shelf matting techniques such as [this](https://grail.cs.washington.edu/projects/background-matting-v2/#/) or reconstruct a mesh from the available views and project it to the image planes. We relied on the latter and reconstructed meshes using the [Reality Capture](https://www.capturingreality.com/realitycapture) software. More details are available in the paper.

**Comment by 2680347338** [comment]
Thank you very much for your reply!
