### ISSUE TITLE
Validation Error

### ISSUE THREAD

**Issue by joon-hh** [synthesiaresearch/humanrf#13]
![image](https://github.com/synthesiaresearch/humanrf/assets/139342734/4b080f23-2668-45e8-a01f-51f6d87e9666)

PC environment : wsl2, cuda 11.8, HumanRF Installation, torch 2.0.1+cu118, 

I used import_dfa.py and reordered DFA panda data.
I tried to run HumanRF with DFA image dataset but I faced the error.
How can I solved it?

![image](https://github.com/synthesiaresearch/humanrf/assets/139342734/0db067ea-0040-4880-b787-383c7e1c17be)
![image](https://github.com/synthesiaresearch/humanrf/assets/139342734/e4f499ed-e2d0-46c0-932f-1a80dc4c3240)

**Comment by gafniguy** [comment]
Hi @joon-hh how did you overcome this? Thanks!
