### ISSUE TITLE
How to extract meshes after training

### ISSUE THREAD

**Issue by zZay** [synthesiaresearch/humanrf#14]
Hi, thanks for releasing the code and data of your great work :)

I want to extract meshes after training on my own data. And I find that a .abc to .obj converter is provided in [actorshq/toolbox], but I have no idea how to get the .abc file after training. Or are there any other methods (e.g., marching cubes) to obtain meshes in this project?

Thank you in advance!

**Comment by isikmustafa** [comment]
Hi, .abc files are only for ground truth meshes. We haven’t provided a way to extract meshes from the neural representation. You can use a library to run marching cubes on the resulting density field.
