### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'vmaf'

### ISSUE THREAD

**Issue by ZhilinGuo** [synthesiaresearch/humanrf#19]
Thanks for the amazing work!

The training can proceed and complete as intended on my end, but an error is thrown when the code calls "vmaf" for evaluation after training is done. Could you let me know what "vmaf" installation it is that I need for evaluation to complete?

```
== Evaluating with 134 frames ==
PSNR: 26.438246794533562
LPIPS: 0.06897718506628897
SSIM: 0.9463056193377604
Traceback (most recent call last):
  File "./humanrf/run.py", line 197, in <module>
    evaluate(
  File "/home/user/humanrf_train/actorshq/evaluation/evaluate.py", line 170, in evaluate
    subprocess.run(
  File "/home/user/.conda/envs/humanrf/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/user/.conda/envs/humanrf/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/user/.conda/envs/humanrf/lib/python3.8/subprocess.py", line 1720, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'vmaf'
terminate called without an active exception
Aborted
```

**Comment by ZhilinGuo** [comment]
Solved by 
1) Downloading vmaf from https://github.com/Netflix/vmaf/releases
2) Adding it to PATH
3) Changing the permission to make the vmaf file executable
4) Restarting terminal

**Comment by qianqiuzzz** [comment]
@ZhilinGuo I met the same error.I have installed vmaf,but there is still the error.I want to know the specific meaning of your step "3.Changing the permission to make the vmaf file executable" and how to operate

**Comment by ZhilinGuo** [comment]
> @ZhilinGuo I met the same error.I have installed vmaf,but there is still the error.I want to know the specific meaning of your step "3.Changing the permission to make the vmaf file executable" and how to operate

Hello, by "3.Changing the permission to make the vmaf file executable" I meant using chmod like this
`chmod +x vmaf`

This will add executable permission to the vmaf file.
