### ISSUE TITLE
Novel pose synthesis

### ISSUE THREAD

**Issue by ArthurMoreau** [synthesiaresearch/humanrf#25]
Thanks for the amazing work with the ActorsHQ dataset.

I would like to evaluate my method on novel pose synthesis and compare with the leaderboard scores but I couldn't find information about the evaluation protocol and data splits. Could you share this information please ?

Thanks again !

**Comment by isikmustafa** [comment]
Unfortunately, it's not possible to send your submission for evaluation right now
