### ISSUE TITLE
Processing for mesh

### ISSUE THREAD

**Issue by YutingXiao** [synthesiaresearch/humanrf#26]
Hi, thanks for this high-quality dataset. I have some questions about the mesh.abc.

I also use Reality Capture to reconstruct a mesh since I want use the UV map and texture map. But the mesh you give seems better than mine, specifically, it is more smooth than ours. So, do you use the original image or masked image for reconstruction ?? Can you provide the UV map of the reconstruction??

**Comment by isikmustafa** [comment]
Hi, we cannot provide that but we ran reality capture on the original (not masked) images. If there is a way to use the camera parameters we provide, please try to use that in the reality capture while generating the mesh.
