### ISSUE TITLE
Login Unsuccessful. Account and email not verified yet.

### ISSUE THREAD

**Issue by zxc524580210** [synthesiaresearch/humanrf#6]
But. I confirm the email has been verified.

**Comment by sora158** [comment]
Also waiting for accepted.

**Comment by s1ddok** [comment]
same here, can't have an access yet, but I see others reporting they received verification

**Comment by louhz** [comment]
Same here

**Comment by YutingXiao** [comment]
Me too, I used 5 mails for sign up, all failed

**Comment by decai-chen** [comment]
same here

**Comment by DarlingHang** [comment]
Same here. Thanks for the excellent work. May the authors take a look at our applications please?

**Comment by Deceptive-NeRF** [comment]
Same here. Could you please consider our request for data access?

**Comment by DanielSHKao** [comment]
Same here. Could you please also consider our request for data access? Thank you!

**Comment by ZhenhuiL1n** [comment]
Same here, please help verify the account. Thanks a lot !!!

**Comment by brianneoberson** [comment]
Same here

**Comment by DragonGateway** [comment]
Same here

**Comment by louhz** [comment]
So my email account has been verified and i send the email with signed document  to the email address, but there is no response!
Can you approve my application
Thanks!

**Comment by sigurdhu** [comment]
Same here

**Comment by starcxl** [comment]
Same here.

**Comment by ZhenhuiL1n** [comment]
> Same here, please help verify the account. Thanks a lot !!!

Hi guys, I asked the author and they replied an amount of  requests will be verified every week. In my case my request got approved after about 2 weeks.

**Comment by three-legs** [comment]
same here

**Comment by ZhenhuiL1n** [comment]
> So my email account has been verified and i send the email with signed document to the email address, but there is no response! Can you approve my application Thanks!

Same here.

**Comment by qianyuling-wl** [comment]
same here

**Comment by isikmustafa** [comment]
Hey everyone, as most of you might've noticed already, we don't have a sign-up procedure any more. You simply send us the release form signed by your PI or group leader, and we send you the links to download the dataset. If you have any other issues, please email to dataset@actors-hq.com.
