### ISSUE TITLE
error: subprocess-exited-with-error, and its solution

### ISSUE THREAD

**Issue by ZhilinGuo** [synthesiaresearch/humanrf#9]
I can install requirements.txt and tiny-cuda-nn by following the instructions, but I encountered `error: subprocess-exited-with-error` when installing ActorsHQ package.

I used `sudo apt-get install libglm-dev` to solve this error.

**Comment by isikmustafa** [comment]
Thank you @ZhilinGuo! I'll add update the readme now.
